// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD__6OPOqDt74vqWhSOigxRAJW9UcqfikU',
    appId: '1:523756741499:web:dd39a60a8e5cdded84d3de',
    messagingSenderId: '523756741499',
    projectId: 'jamu-saripah-78774',
    authDomain: 'jamu-saripah-78774.firebaseapp.com',
    storageBucket: 'jamu-saripah-78774.firebasestorage.app',
    measurementId: 'G-4CZGNDS9ZJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBymYUiuQeqzolGvFnixdk9-6xGu4ROBRs',
    appId: '1:523756741499:android:da218b19466f56d584d3de',
    messagingSenderId: '523756741499',
    projectId: 'jamu-saripah-78774',
    storageBucket: 'jamu-saripah-78774.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVBacHEvpoFbeD831lSrPQOIhTmYKkGdM',
    appId: '1:523756741499:ios:38dceb2753b7eda184d3de',
    messagingSenderId: '523756741499',
    projectId: 'jamu-saripah-78774',
    storageBucket: 'jamu-saripah-78774.firebasestorage.app',
    iosBundleId: 'com.example.jamuSaripah',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVBacHEvpoFbeD831lSrPQOIhTmYKkGdM',
    appId: '1:523756741499:ios:38dceb2753b7eda184d3de',
    messagingSenderId: '523756741499',
    projectId: 'jamu-saripah-78774',
    storageBucket: 'jamu-saripah-78774.firebasestorage.app',
    iosBundleId: 'com.example.jamuSaripah',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD__6OPOqDt74vqWhSOigxRAJW9UcqfikU',
    appId: '1:523756741499:web:a082973468c0977384d3de',
    messagingSenderId: '523756741499',
    projectId: 'jamu-saripah-78774',
    authDomain: 'jamu-saripah-78774.firebaseapp.com',
    storageBucket: 'jamu-saripah-78774.firebasestorage.app',
    measurementId: 'G-XGCMMK6JB6',
  );

}